### ISSUE TITLE
Example not valid for Sitefinity 10

### ISSUE THREAD

**Issue by OndeVai** [Sitefinity/Sitefinity-External-STS-Integration#21]
This example is not valid for Sitefinity 10, becuase the SecurityTokenServiceHttpHandler class has been removed.

**Comment by syedhaider123** [comment]
Is there any equivalent for SecurityTokenServiceHttpHandler in Sitefinity 10

**Comment by todorm85** [comment]
Hi all,
this example is only valid for versions <=9.2. For Sitefinity >=10.0 it is OOB feature. See documentation: https://docs.sitefinity.com/administration-configure-external-identity-providers
